# Generated by Django 2.2.7 on 2019-11-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nikename', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('pic_url', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[(0, '女'), (1, '男')], max_length=1, null=True)),
                ('status', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
